### PR TITLE
Fix crash when asking grdcut to output file with no extension.

### LINKED ISSUE #8537: grdcut: segmentation fault if output extension is omitted
See forum for details:  https://forum.generic-mapping-tools.org/t/error-recognizing-tif-files-from-remote-dataset/5035/7

I offer to fix it (with Joaquim guidance).

The source code should be fixed. I think I will have to edit this file: 
https://github.com/GenericMappingTools/gmt/blob/master/src/grdcut.c

### PR DESCRIPTION
**Pull request by joa-quim**
Fix #8537

### CODE REVIEW

File: src/gmt_gdalwrite.c [hunk 1]
```diff
@@ -102,7 +102,11 @@ int gmt_export_image (struct GMT_CTRL *GMT, char *fname, struct GMT_IMAGE *I) {
 		to_GDALW->ULy = I->header->n_rows;
 	}
 
-	ext = gmt_get_ext (fname);
+	ext = gmt_get_ext(fname);
+	if (ext == NULL) {
+		GMT_Report(GMT->parent, GMT_MSG_ERROR, "Cannot NOT provide a file extension for the saving file (-G option). We need it to determine the output format.\n");
```
Comment (seisman) [inline src/gmt_gdalwrite.c:107]:
```suggestion
		GMT_Report(GMT->parent, GMT_MSG_ERROR, "Can NOT provide a file extension for the saving file (-G option). We need it to determine the output format.\n");
```

**Review by seisman — APPROVED** [review]

File: src/gmt_gdalwrite.c (hunk 1 above)
Comment (joa-quim) [reply src/gmt_gdalwrite.c]: OK, rephrased it to "MUST provide ..."
