### PR TITLE
Use docutils version 0.16 to build gmt docs

### LINKED ISSUE #5097: Broken formatting with docutils 0.17 #1176
**Description of the problem**

Same issue as https://github.com/GenericMappingTools/pygmt/issues/1176, but more extensively affects the GMT documentation front page, in that the quicklinks section and toctree are both now formatted poorly:

image

image

### PR DESCRIPTION
**Pull request by meghanrjones**
**Description of proposed changes**

The 0.17 docutils release broke much of the formatting for the sphinx_rtd_theme. This PR pins the docutils dependency of sphinx to v0.16.

Fixes #5097 

**Reminders**

- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

File: ci/install-dependencies-linux.sh [hunk 1]
```diff
@@ -42,7 +42,7 @@ sudo apt-get install -y --no-install-recommends --no-install-suggests $packages
 # Install more packages for building documentation
 if [ "$BUILD_DOCS" = "true" ]; then
     sudo snap install pngquant
-    pip3 install --user sphinx
+    pip3 install --user docutils==0.16 phinx
```
Comment (seisman) [inline ci/install-dependencies-linux.sh:45]:
```suggestion
    pip3 install --user docutils==0.16 sphinx
```

**Review by seisman — CHANGES_REQUESTED** [review]

**Review by seisman — APPROVED** [review]
Good to merge after fixing the typo
