### PR TITLE
Just use a system call to wipe the entire sessions dir

### LINKED ISSUE #3476: gmt clear fails on Win if session dirs are not empty
```
gmt clear sessions
c:/j/.gmt/sessions: Directory not empty
```

### PR DESCRIPTION
**Pull request by PaulWessel**
No safety issues since this directory was created by GMT. See #3476 for discussion. It does not matter if the user has set their **USER_DIR** to any area, since we _only_ delete the subdirectory _sessions_ inside that directory.  GMT created it, so GMT can delete it.  Closes #3476.

### CODE REVIEW

File: src/clear.c [hunk 1]
```diff
@@ -151,35 +151,23 @@ static int clear_data (struct GMTAPI_CTRL *API, char *planet) {
...
-	char **dirlist = NULL, *here = NULL;
+	int error;
+	char del_cmd[PATH_MAX] = {""};
 	if (access (API->session_dir, F_OK)) {
 		GMT_Report (API, GMT_MSG_INFORMATION, "No directory named %s\n", API->session_dir);
 		return GMT_FILE_NOT_FOUND;
 	}
-	if ((here = getcwd (NULL, 0)) == NULL) {	/* Get the current directory */
-		GMT_Report (API, GMT_MSG_ERROR, "Cannot determine current directory!\n");
+#ifdef WIN32
```
Comment (joa-quim) [inline src/clear.c:160]: My only doubt is this bloody macro. Never clearly understood the difference for ``_WIN32`` but I think thing both MinGW and VS define it, whilst Cygwin has a ``WIN32``. For playing safe I would prefer it to be ``_WIN32``

**Comment by PaulWessel** [comment]
@joa-quim may wish to check that we are consistently using WIN32 vs _WIN32.  I believe _WIN32 is set by the MicroSoft compiler only and hence it is pure Windows, while WIN32 may be set under both Windows and Cygwin.  So pure Windows API calls should be _WIN32.

**Comment by joa-quim** [comment]
Not that obvious. MinGW defines ``_WIN32`` too. The big problem is that we never built/tested MinGW and Cygwin builds. When we want to restrict to VS we should is use ``_MSC_VER`` but then it also has versions.

**Comment by PaulWessel** [comment]
This says things starting with underscore is for compilers providers: https://stackoverflow.com/questions/662084/whats-the-difference-between-the-win32-and-win32-defines-in-c

**Comment by joa-quim** [comment]
I was reading that same post

**Comment by PaulWessel** [comment]
Well, price we pay for supporting a non-Posix OS!
OK to merge this?

**Comment by seisman** [comment]
> The big problem is that we never built/tested MinGW and Cygwin builds. 

Azure Pipepines already have MinGW installed. It seems straightforward to test GMT with MinGW.

**Comment by joa-quim** [comment]
... still don't understand what's so f different between them.

**Comment by joa-quim** [comment]
> Azure Pipepines already have MinGW installed. It seems straightforward to test GMT with MinGW.

That is right, but I really don't feel like start maintaining another build system.

**Comment by seisman** [comment]
It seems there are very few people using Cygwin.

**Comment by joa-quim** [comment]
Yes, and there even less (0 to my knowledge) BUILDING (try at least) in Cygwin.

**Comment by PaulWessel** [comment]
still need to get go-ahead to merge though.

**Comment by joa-quim** [comment]
You have two (but need none)
