### PR TITLE
make/grd2cpt: Ensure that if -C is given it has an argument

### LINKED ISSUE #4459: Check if the CPT name is empty
Here is the command to reproduce the issue:
```
$ gmt grd2cpt @earth_relief_01d -C -R0/10/0/10 > 123.cpt
grd2cpt [ERROR]: CPT gmtapi_colors2cpt_77472.cpt has no z-slices!
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
[Session gmt (0)]: Error returned from GMT API: GMT_CPT_READ_ERROR (8)
```

It looks like a user error, but at least we should improve the error message.

### PR DESCRIPTION
**Pull request by PaulWessel**
While there are default CPTs, these only go into effect if **-C** is _not_ given.  If **-C** _is_ given with _no_ argument it is an error, now caught by both **makecpt** and **grd2cpt**.  Closes #4459.

### CODE REVIEW

File: src/grd2cpt.c [hunk 1]
```diff
@@ -421,10 +421,14 @@ static int parse (struct GMT_CTRL *GMT, struct GRD2CPT_CTRL *Ctrl, struct GMT_OP
 		}
 	}
 
-	if (Ctrl->H.active && GMT->current.setting.run_mode == GMT_CLASSIC) {
-		n_errors++;
-		GMT_Report (GMT->parent, GMT_MSG_ERROR, "Unrecognized option -H\n");
+	if (GMT->current.setting.run_mode == GMT_CLASSIC) {
+		if (Ctrl->H.active) {
+			n_errors++;
+			GMT_Report (GMT->parent, GMT_MSG_ERROR, "Unrecognized option -H\n");
```
Comment (joa-quim) [inline src/grd2cpt.c:427]: It would be better to say that "-H option is not valid in classic mode". Or even better, just ignore it silently.

Comment (PaulWessel) [reply src/grd2cpt.c]: OK, and I changed it to a warning.  Not a fan of silence for wrong use.

**Review by seisman — APPROVED** [review]

File: src/grd2cpt.c (hunk 1 above)
Comment (joa-quim) [reply src/grd2cpt.c]: OK, but remember that sometimes the commands were not written by humans.

**Review by joa-quim — APPROVED** [review]
